// app/layout.tsx
import 'swiper/css';
import 'swiper/css/autoplay';
import type { Metadata } from 'next';
import { Forum, Inter } from 'next/font/google';
import './globals.css';

// Load font Inter
const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  weight: ['400', '700'],
});

const forum = Forum({
  subsets: ['latin'],
  variable: '--font-forum',
  weight: ['400'], // <- tambahkan ini
});


export const metadata: Metadata = {
  title: 'AslamMaulana',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${forum.variable} antialiased bg-[#0a0a0a]`}>
        {children}
      </body>
    </html>
  );
}
